
require 'methadone'
require 'fog'
require 'vcloud/core'
require 'pp'

require 'vcloud/cli/utils/get_entity'
require 'vcloud/cli/utils/stop_vapp'
require 'vcloud/cli/utils/start_vapp'
require 'vcloud/cli/utils/delete_vapp'
require 'vcloud/cli/utils/delete_network'
require 'vcloud/cli/utils/make_vapp_template'
require 'vcloud/cli/utils/create_disk'
require 'vcloud/cli/utils/attach_disk'
require 'vcloud/cli/utils/detach_disk'
require 'vcloud/cli/utils/delete_disk'
